name: Import Training Blog

on:
  # Run on a schedule (daily at midnight UTC)
  schedule:
    - cron: "0 0 * * *"
  # Allow manual trigger from the Actions tab
  workflow_dispatch:

jobs:
  import-blog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Import Training Blog 📚
        run: |
          python import_training_blog.py

      - name: Check for changes
        id: git-check
        run: |
          git status --porcelain
          echo "changes=$(git status --porcelain | wc -l)" >> $GITHUB_OUTPUT

      - name: Commit changes
        if: steps.git-check.outputs.changes > 0
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add _blogs/training-at-larger-scale/
          git add images/training-blog/
          git commit -m "Auto-update training blog from source repository"

      - name: Push changes
        if: steps.git-check.outputs.changes > 0
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
