name: Update External Blogs

on:
  schedule:
    - cron: "0 0 * * *" # Run every day at midnight
  workflow_dispatch: # Allow manual triggering

jobs:
  update-external-blogs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
          bundler-cache: true

      - name: Update submodules
        run: |
          git submodule update --remote --recursive

      - name: Process external blog files
        run: |
          mkdir -p _external_blogs
          ruby _scripts/process_external_blogs.rb

      - name: Commit changes if any
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add _external_blogs/
          git add _external_blogs/training-at-scale/
          git diff --staged --quiet || git commit -m "Update external blog content"
          git push
